# this is the version the bot will _hopefully_ pick up and PR.
{% set version = "3.9.0" %}
# Leave the build number the same if only the server version changes.
{% set build_number = 0 %}

# this will likely have to be hand-updated.
{% set server_version = "1.4.1" %}
# Leave the build number the same if only the labextension changes.
{% set server_build_number = 0 %}

# List of jupyter_lsp py.tests ran for each known servers
{% set server_tests = ["serverextension", "start_known", "listeners"] %}

package:
  name: jupyter-lsp-meta  # To avoid issue https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  - folder: jupyterlab-lsp
    url: https://pypi.io/packages/source/j/jupyterlab-lsp/jupyterlab-lsp-{{ version }}.tar.gz
    sha256: 40b3cf18c4f9299af4d88096290ad28750418f75e791f68a2a1f6891bb1dce9e
  - folder: jupyter-lsp
    url: https://pypi.io/packages/source/j/jupyter-lsp/jupyter-lsp-{{ server_version }}.tar.gz
    sha256: 3b423ab38c93c8b951a0c20cc4c0ba56920cde09b226001353b967b1e5bcfae2

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "TBD"

outputs:
  - name: jupyterlab-lsp
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script: cd jupyterlab-lsp && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - jupyter-lsp >={{ server_version }}
        - jupyterlab >=3,<4
        - python >=3.6
    test:
      requires:
        - pip
      commands:
        - pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "jupyterlab-lsp.*OK.*jupyterlab-lsp"  # [unix]
        # tests nbclassic machinery
        - jupyter serverextension list
        - jupyter serverextension list 1>serverextensions 2>&1
        - cat serverextensions | grep "jupyter_lsp.*OK"  # [unix]

    about:
      home: https://github.com/jupyter-lsp/jupyterlab-lsp
      license_file: jupyterlab-lsp/LICENSE
      license: BSD-3-Clause
      license_family: BSD
      summary: Language Server Protocol integration for JupyterLab
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
      script: cd jupyter-lsp && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - entrypoints
        - jupyter_server >=1.1.2
        - python >=3.6
    test:
      requires:
        - pip
      commands:
        - pip check
        - jupyter server extension list
        - jupyter server extension list 1>serverextensions 2>&1
        - cat serverextensions | grep "jupyter_lsp.*OK"  # [unix]
    about:
      home: https://github.com/jupyter-lsp/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: Multi-Language Server WebSocket proxy for Jupyter Server
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp-latex
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("jupyter-lsp", exact=True) }}
        - texlab
        - chktex
    test:
      requires:
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - pip check
        # TODO add test for current ls by adding " or pyls" to -k option - but 1 test is failing
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }} or r_package_detection)"
    about:
      home: https://github.com/jupyter-lsp/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: A metapackage for jupyter-lsp and texlab
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp-python
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("jupyter-lsp", exact=True) }}
        - python-lsp-server >=1
    test:
      requires:
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - pip check
        # TODO add test for current ls by adding " or pyls" to -k option - but 1 test is failing
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }} or r_package_detection)"
    about:
      home: https://github.com/jupyter-lsp/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: A metapackage for jupyter-lsp and python-lsp-server
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp-python-plugins
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("jupyter-lsp-python", exact=True) }}
        - pyls-isort >=0.2.2
        - pylsp-mypy >=0.5.1
        - pyls-memestra >=0.0.13

    test:
      requires:
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - pip check
        # TODO add test for current ls by adding " or pyls" to -k option - but 1 test is failing
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }} or r_package_detection)"
    about:
      home: https://github.com/jupyter-lsp/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: A metapackage for jupyter-lsp, python-language-server, and all known plugins
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs

  - name: jupyter-lsp-r
    version: {{ server_version }}
    build:
      number: {{ server_build_number }}
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("jupyter-lsp", exact=True) }}
        # Snippets support https://github.com/jupyter-lsp/jupyterlab-lsp/issues/208
        - r-languageserver >=0.3.5
    test:
      requires:
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - pip check
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }})"
    about:
      home: https://github.com/jupyter-lsp/jupyterlab-lsp
      license: BSD-3-Clause
      license_family: BSD
      license_file: jupyter-lsp/LICENSE
      summary: A metapackage jupyter-lsp and r-languageserver
      doc_url: https://jupyterlab-lsp.readthedocs.io
      doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs


about:
  home: https://github.com/jupyter-lsp/jupyterlab-lsp
  license: BSD-3-Clause
  license_family: BSD
  license_file: jupyterlab-lsp/LICENSE
  summary: Multi-Language Server WebSocket proxy for Jupyter Server
  doc_url: https://jupyterlab-lsp.readthedocs.io
  doc_source_url: https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs

extra:
  feedstock-name: jupyter-lsp
  recipe-maintainers:
    - bollwyvl
    - fcollonval
    - krassowski
