{% set name = "jupyter-lsp" %}
{% set ext_name = "@krassowski/jupyterlab-lsp" %}
{% set version = "0.9.1" %}
{% set build_number = 1 %}

{% set py_spec = ">=3.5" %}
{% set lab_spec = ">=2,<2.2.0a0" %}
{% set ext_spec = "@^1.1.2" %}

# List of jupyter_lsp py.tests ran for each known servers
{% set server_tests = ["serverextension", "start_known", "listeners"] %}

package:
  name: {{ name }}-meta  # To avoid issue https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb954763ccc411cf6b75c18854c19078f05b1e774f0df53f066c44458d655c8e

build:
  noarch: python
  number: {{ build_number }}

outputs:
  - name: {{ name }}
    build:
      number: {{ build_number }}
      noarch: python
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - pip
        - python {{ py_spec }}
      run:
        - notebook >=4.3.1
        - python {{ py_spec }}
        - setuptools
    test:
      requires:
        - jupyterlab {{ lab_spec }}
        - jupyterlab_server>=1.1.0
        - nodejs >=10
        - pip
      commands:
        - python -m pip check
        - jupyter serverextension list 1>serverextensions 2>&1
        - cat serverextensions | grep "{{ name|replace("-", "_") }}.*OK"  # [unix]
        - jupyter labextension install {{ ext_name }}{{ ext_spec }}
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "{{ ext_name }}.*OK"  # [unix]
        - python -m jupyterlab.browser_check  # [not linux]
  - name: {{ name }}-python
    build:
      number: {{ build_number }}
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        - python-language-server >=0.31.9
    test:
      requires:
        - jupyterlab {{ lab_spec }}
        - jupyterlab_server>=1.1.0
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - python -m pip check
        # TODO add test for current ls by adding " or pyls" to -k option - but 1 test is failing
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }})"
    about:
      summary: A metapackage for jupyter-lsp and python-language-server
  - name: {{ name }}-r
    build:
      number: {{ build_number }}
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        # Snippets support https://github.com/krassowski/jupyterlab-lsp/issues/208
        - r-languageserver >=0.3.5
    test:
      requires:
        - jupyterlab {{ lab_spec }}
        - jupyterlab_server>=1.1.0
        - pip
        - pytest-asyncio
        - pytest-runner
      commands:
        - python -m pip check
        # TODO add test for current ls
        - pytest -vv -p no:warnings --pyargs jupyter_lsp -k "not ({{ server_tests|join(' or ') }})"
    about:
      summary: A metapackage jupyter-lsp and r-languageserver

about:
  home: https://github.com/krassowski/jupyterlab-lsp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Multi-Language Server WebSocket proxy for Jupyter notebook or lab server for Python 3.5+.
  doc_url: https://jupyterlab-lsp.readthedocs.io
  doc_source_url: https://github.com/krassowski/jupyterlab-lsp/blob/v{{ version }}/docs

extra:
  feedstock-name: {{ name }}
  recipe-maintainers:
    - bollwyvl
    - fcollonval
    - krassowski
